name: "Tom Hohenstein"
description: "experiements and thoughts"
author: "Tom Hohenstein"

# url: "http://tomhohenstein.com"
url: "http://tomhohenstein.com"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title

gems: [jekyll-paginate]